### ISSUE TITLE
Create Use Case Flow Pseudo Code

### ISSUE THREAD

**Issue by ka05** [ka05/tiger-books#10]
Ex:

if(userLoggedInAlready){ 
  showProfilePage()
}else{
  showLogin()
}

**Comment by coffeeScripter** [comment]
I hate you.

**Comment by ka05** [comment]
This will need to be separated into different sections based on different use cases. Seriously though, this will help tremendously!

**Comment by coffeeScripter** [comment]
moved to wiki @ https://github.com/ka05/tiger-books/wiki/Pseudo-Code-Flow-Cases
