### ISSUE TITLE
Research and Report on RBAC

### ISSUE THREAD

**Issue by ka05** [ka05/tiger-books#14]
Role-based access control (RBAC) is a method of regulating access to computer or network resources based on the roles of individual users within an enterprise. In this context, access is the ability of an individual user to perform a specific task, such as view, create, or modify a file.

Node.js module for RBAC
Look at: https://www.npmjs.com/package/rbac2

**Comment by coffeeScripter** [comment]
http://jedireza.github.io/drywall/ check this ALSO MOVE TO WIKI ALL RESEARCH JUNK SO IT IS ONE PLACE
