### ISSUE TITLE
Research and Report on "Node.js REST Login"

### ISSUE THREAD

**Issue by ka05** [ka05/tiger-books#5]
Look into different node modules that exist for this sole purpose that will make our lives easier

**Comment by ka05** [comment]
possible solution: http://thejackalofjavascript.com/architecting-a-restful-node-js-app/

**Comment by ka05** [comment]
some other ideas: http://stackoverflow.com/questions/15496915/how-to-implement-a-secure-rest-api-with-node-js

**Comment by coffeeScripter** [comment]
Changing this to be a wiki page
