### ISSUE TITLE
Finish User Profile Image handler

### ISSUE THREAD

**Issue by ka05** [ka05/tiger-books#8]
V 2.0 type of addition : Ideally we want to grab the user's "mycourses" image if it exists. Otherwise allow them to "take pic" or "upload pic"

**Comment by coffeeScripter** [comment]
I would like to keep this a separate from RIT as possible specifically so clones can be used by other people at other universities. This also means that we don't have to worry about getting permission from RIT. I mean we put this on git so other people can clone it? Am I right or did I just misinterpret that?

**Comment by ka05** [comment]
Idk, we put it on here because git is made for collaboration and we are working on this together. I agree with you on this.
